# Generated by Django 5.2.2 on 2025-06-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0002_alter_category_options_alter_product_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Имя картинки')),
                ('image', models.ImageField(upload_to='gallery')),
            ],
        ),
    ]
