# Generated by Django 5.2.2 on 2025-06-05 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0003_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name': 'Галерея', 'verbose_name_plural': 'Галерея'},
        ),
    ]
