# Generated by Django 5.2.2 on 2025-06-05 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0005_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='featured',
            field=models.BooleanField(verbose_name='Наличие'),
        ),
    ]
