# Generated by Django 5.2.2 on 2025-06-05 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0008_alter_review_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='description',
            field=models.TextField(blank=True, max_length=500, verbose_name='Описание'),
        ),
    ]
