# Generated by Django 5.2.2 on 2025-06-06 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0012_aboutfarm_alter_hero_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutfarm',
            options={'verbose_name': 'О ферме', 'verbose_name_plural': 'О ферме'},
        ),
    ]
