# Generated by Django 5.2.2 on 2025-06-06 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0013_alter_aboutfarm_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutfarm',
            name='image',
        ),
        migrations.AddField(
            model_name='aboutfarm',
            name='icon_class',
            field=models.CharField(choices=[('fas fa-egg', 'Яйцо'), ('fas fa-kiwi-bird', 'Перепёлка'), ('fas fa-crow', 'Курица (стилизовано)'), ('fas fa-feather', 'Птицеводство'), ('fas fa-carrot', 'Овощи'), ('fas fa-apple-alt', 'Фрукты'), ('fas fa-cheese', 'Молочные продукты'), ('fas fa-seedling', 'Зелень'), ('fas fa-wheat', 'Зерновые'), ('fas fa-cow', 'Мясо'), ('fas fa-leaf', 'Экология'), ('fas fa-tractor', 'Техника'), ('fas fa-hands', 'Ручная работа')], default='fas fa-leaf', max_length=50, verbose_name='Класс иконки'),
        ),
    ]
