# Generated by Django 5.2.2 on 2025-06-06 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0015_contacts'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('base_url', models.URLField()),
                ('icon_class', models.CharField(choices=[('fab fa-vk', 'VK'), ('fab fa-telegram', 'Telegram'), ('fab fa-whatsapp', 'WhatsApp'), ('fab fa-instagram', 'Instagram'), ('fab fa-youtube', 'YouTube')], default='fab fa-telegram', max_length=50, verbose_name='Класс иконки')),
            ],
        ),
    ]
