# Generated by Django 5.2.2 on 2025-06-06 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lending', '0016_socialnetwork'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socialnetwork',
            options={'verbose_name': 'Социальная сеть', 'verbose_name_plural': 'Социальные сети'},
        ),
    ]
